# SMS module
# Transmitting AT Commands to the Modem
# '\r\n' indicates the Enter key
import serial
import os, time

# Enable Serial Communication
port = serial.Serial("/dev/ttyS0", baudrate=9600, timeout=1)

# Variables
# User info
name = ''
sex = ''
birthday = ''
contact = ''

#Vitals
body_temperature = ''
body_temperature_stat = ''

pulse_rate = ''
pulse_rate_stat = ''

systolic_bp = ''
systolic_bp_stat = ''

diastolic_bp = ''
diastolic_bp_stat = ''

oxygen_saturation = ''
oxygen_saturation_stat = ''

#Diff Diag



port.write('AT'.encode())         # Enter AT Mode
port.write('\r\n'.encode())
time.sleep(1)

port.write('AT'.encode())         # Double this to confirm start
port.write('\r\n'.encode())
time.sleep(1)

port.write('ATE0'.encode())       # Disable the Echo
port.write('\r\n'.encode())
time.sleep(1)

port.write('AT+CMGF=1'.encode())  # Select Message format as Text mode
port.write('\r\n'.encode())
time.sleep(1)

# port.write('AT+CNMI=2,1,0,0,0'+'\r\n')   # New SMS Message Indications
# rcv = port.read(10)
# print rcv
# time.sleep(1)

port.write('AT+CMGS="{}"'.format(contact_no).encode()) # Send a message to Number
port.write('\r\n'.encode())
time.sleep(1)

# Message content
port.write('''HIGH GROUNDS HEALTH KIOSK PATIENT ASSESSMENT

NAME: JUAN DELA CRUZ
SEX: MALE
BIRTHDAY: April 20, 1988
CONTACT: 09953148843

Vital Signs:
- Body Temperature: 37 °C - STATUS
- Pulse Rate: 70 bpm - STATUS
- Systolic Blood Pressure: 120 mmHg - STATUS
- Diastolic Blood Pressure: 80 mmHg - STATUS
- Oxygen Saturation: 98 % - STATUS

Differential Diagnosis:
- HYPERTENSIVE DISEASE
- DIABETES
- CORONARY ARTERIOSCLEROSIS
- CORONARY HEART DISEASE
- ACCIDENT CEREBROVASCULAR

This is an autogenerated message from HIGH GROUNDS HEALTH KIOSK'''.encode())

port.write('\r\n'.encode())
print("NUMBER:",contact_no)
port.write("\x1A".encode()) # Enable to send SMS
for i in range(10):
    rcv = port.read(10)
    print(rcv)