# Generated by Django 4.0.3 on 2022-04-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
