# Generated by Django 4.0.3 on 2022-04-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patient_age_patient_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_added']},
        ),
    ]
