# Generated by Django 4.0.3 on 2022-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='differentials',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
