import serial
import os
import time

# Enable Serial Communication
port = serial.Serial("/dev/ttyS0", baudrate=9600, timeout=1)


def sendSms(resultForm):
    name = '{} {}'.format(resultForm['first_name'], resultForm['last_name'])
    sex = resultForm['sex']
    birth_date = resultForm['birth_date']
    contact_no = resultForm['contact_no']
    symptoms = resultForm['symptoms']
    differentials = resultForm['differentials']
    temperature = resultForm['temperature']
    pulse_rate = resultForm['pulse_rate']
    systolic_bp = resultForm['systolic_bp']
    diastolic_bp = resultForm['diastolic_bp']
    o2_saturation = resultForm['o2_saturation']

    contact_no = contact_no.replace('0', '+63', 1)
    contact_no = contact_no.replace('-', '')
    contact_no = contact_no.replace(' ', '')

    # Message content
    msg = '''
    HIGH GROUNDS HEALTH KIOSK PATIENT ASSESSMENT

    NAME: {}
    SEX: {}
    BIRTHDAY: {}
    CONTACT: {}

    Vital Signs:
    - Body Temperature: {} °C - {}
    - Pulse Rate: {} bpm - {}
    - Systolic Blood Pressure: {} mmHg - {}
    - Diastolic Blood Pressure: {} mmHg - {}
    - Oxygen Saturation: {} % - {}

    '''.format(name, sex, birth_date, contact_no, temperature['value'], temperature['status'], pulse_rate['value'], pulse_rate['status'], systolic_bp['value'], systolic_bp['status'], diastolic_bp['value'], diastolic_bp['status'], o2_saturation['value'], o2_saturation['status'])

    print("Differentials: ", differentials)
    if (differentials != None):
        heading = '''

        Differential Diagnosis:

        '''

        msg.join(heading)

        diff = ""
        for differential in differentials:
            diff.join('- {}\n'.format(differential))

        msg.join(diff)

    msg.join("\n\nThis is an autogenerated message from HIGH GROUNDS HEALTH KIOSK")

    print(msg)

    port.write('AT'.encode())         # Enter AT Mode
    port.write('\r\n'.encode())
    time.sleep(1)

    port.write('AT'.encode())         # Double this to confirm start
    port.write('\r\n'.encode())
    time.sleep(1)

    port.write('ATE0'.encode())       # Disable the Echo
    port.write('\r\n'.encode())
    time.sleep(1)

    port.write('AT+CMGF=1'.encode())  # Select Message format as Text mode
    port.write('\r\n'.encode())
    time.sleep(1)

    # Send a message to Number
    port.write('AT+CMGS="{}"'.format(contact_no).encode())
    port.write('\r\n'.encode())
    time.sleep(1)

    port.write(msg.encode())

    port.write('\r\n'.encode())
    print("NUMBER:", contact_no)
    port.write("\x1A".encode())  # Enable to send SMS
    for i in range(10):
        rcv = port.read(10)
        print(rcv)

    return 200
