# Generated by Django 4.0.3 on 2022-04-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_profile_contact_no_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.profile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('NOTIFIED', 'NOTIFIED'), ('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200, null=True),
        ),
    ]
