# Generated by Django 4.0.3 on 2022-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_appointment_assigned_personnel_appointment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('NOTIFIED', 'NOTIFIED'), ('COMPLETE', 'COMPLETE'), ('DISCARDED', 'DISCARDED')], max_length=200, null=True),
        ),
    ]
