# Generated by Django 4.0.3 on 2022-05-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date']},
        ),
    ]
